### ISSUE TITLE
ImportError: Could not import llama-cpp-python library

### ISSUE THREAD

**Issue by user1679user1679** [Aesthisia/LLMinator#44]
Running webui.py after fixing #42 yields: 
![image](https://github.com/Aesthisia/LLMinator/assets/170612240/d6c55152-b182-4ee9-88ad-2e5dd7fca785)
 
This is also on a fresh system, after installing requirements and make-ing without errors. Also tried in a fresh conda env, and on the base python default in the ubuntu machine.

``pip install llama-cpp-python`` says it's already installed. Any thoughts? Thanks

**Comment by parveen232** [comment]
@user1679user1679 Try this
```
pip install --upgrade --force-reinstall --no-cache-dir llama-cpp-python
```
